preview_homepage:
    pattern:  /home/{_locale}
    defaults: { _controller: scrclubSCRClubBundle:Default:index, _locale:fr }

page:
    pattern:  /page/{_locale}/{slug}
    defaults: { _controller: scrclubSCRClubBundle:Default:page, _locale:fr }

intro:
    pattern:  /
    defaults: { _controller: scrclubSCRClubBundle:Default:index, _locale:fr }